version: '3.7'

networks:
  marklogicDHF:

services:
    marklogic.dhf.local:
      image: store/marklogicdb/marklogic-server:${mlVersion}
      hostname: ${stackName}.dhf.local
      container_name: ${stackName}.dhf.local
      environment:
        - MARKLOGIC_INIT=true
        - MARKLOGIC_ADMIN_USERNAME=${mlAdmin}
        - MARKLOGIC_ADMIN_PASSWORD=${mlPassword}
        - TZ=Europe/Prague
      ports:
        - ${markLogicPortMapping}:${mlPortRange}
      volumes:
        - ./volumes/${stackName}.dhf.local/:/var/opt/MarkLogic/:delegated
      networks:
        - marklogicDHF


    quick.start:
      build: 
        context: .
        dockerfile: quickstart.Dockerfile
        args:
          - quickstart_download_url=${quickStartURL}
      image: quick.start
      environment:
        - SERVER_PORT=${quickstartPort}
        - MARKLOGIC_ADMIN_USERNAME=${mlAdmin}
        - MARKLOGIC_ADMIN_PASSWORD=${mlPassword}
        - STACK_NAME=${stackName}
        - DHF_VERSION=${DHFversion}
      depends_on:     
        - marklogic.dhf.local
      hostname: ${stackName}.quick_start
      container_name: ${stackName}.quick_start
      ports:
       - ${quickStartPortMapping}:${quickstartPort}
      volumes:
       - ${DHFfiles}:/DHF-config:delegated
       - ./data:/data:delegated
      networks:
       - marklogicDHF  

    pipes:
      build: 
        context: .
        dockerfile: pipes.Dockerfile
        args:
          - pipes_download_url=${pipesURL}
      image: dhf.pipes
      environment:
        - MLHOST={$STACK_NAME}.dhf.local
        - SERVER_PORT=${pipesPort}
        - MARKLOGIC_ADMIN_USERNAME=${mlAdmin}
        - MARKLOGIC_ADMIN_PASSWORD=${mlPassword}
        - STACK_NAME=${stackName}
        - ADMIN_PORT=${mlAdminPort}
        - APPSERVICES_PORT=${mlAppServicesPort}
        - MANAGE_PORT=${mlManagePort}
        - STAGING_PORT=${mlStagingPort}
      depends_on: 
        - marklogic.dhf.local
      container_name: ${stackName}.pipes
      ports:
       - ${pipesPortMapping}:${pipesPort}
      volumes:
        - ${DHFfiles}:/DHF:delegated
        - ./data:/data:delegated
      networks:
        - marklogicDHF